### ISSUE TITLE
First-Time Settings Incorrect (Dev)

### ISSUE THREAD

**Issue by stegsaurus** [stuartsoft/PingIT#25]
When the user opens the app for the first time, the ringtone, delay number, and name fields are incorrect. The ringtone should be the phone's default ringtone, the name should be their entered name at registration, and the delay value should be something other than null (5 minutes?)

See image for what this looks like:

https://files.slack.com/files-pri/T09LPUR3K-F0YKXR8MQ/2016-04-07_00.29.03.png

**Comment by JSybrandt** [comment]
now they are correct
10 minutes
