### ISSUE TITLE
FAQ Visuals/Scrolling Needs Work (Dev)

### ISSUE THREAD

**Issue by stegsaurus** [stuartsoft/PingIT#26]
The FAQ is functional, but it needs some polishing. Questions shouldn't awkwardly scroll inside their little window, the justification is off, and we need to test to be sure that when the categories go past the bottom of the screen everything looks good.

**Comment by stuartsoft** [comment]
I made the FAQ page nested lists larger after talking to Justin. Increased size from 150dp to 250dp.
