### ISSUE TITLE
Memory Leaks (Dev)

### ISSUE THREAD

**Issue by stegsaurus** [stuartsoft/PingIT#31]
We haven't been able to pinpoint this yet, but we need to fix the memory leak. We should utilize Fabric and LeakCanary here.

**Comment by stuartsoft** [comment]
Justin has been looking into this specifically. I believe he said it is coming from an issue with the chat page. To prevent LeakCanary from freezing, make sure the storage permission is enabled on the app on your phone.

**Comment by JSybrandt** [comment]
the only memory leak currently in is in zared's callback if theres a weird interaction with settings. The passive memory leak is fixed.

**Comment by JSybrandt** [comment]
30 minutes
